# Generated by Django 3.2 on 2025-01-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together={('email', 'username')},
        ),
    ]
