# Generated by Django 3.2 on 2025-01-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250106_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
